<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <VersionPrefix>0.192.1</VersionPrefix>
        <Authors>R'laf | 阿乐夫</Authors>
        <!-- <Company>Company Name</Company> -->
        <!-- <Product>Product Name</Product> -->
        <Title>libgit2 native runtimes for git-taut</Title>
        <PackageId>Lg2.native</PackageId>
        <PackageDescription>libgit2 native runtimes for git-taut</PackageDescription>
        <PackageProjectUrl>https://github.com/rlaf99/libgit2</PackageProjectUrl>
        <PackageTags>Lg2 libgit2 git-taut</PackageTags>
	<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoWarn>NU5128</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <None Include="packaging\LICENSE.md"
              Pack="true"
              Visible="false"
              PackagePath="" />
        <None Include="packaging\README.md"
              Pack="true"
              Visible="false"
              PackagePath="" />
        <None Include="packaging\Lg2.native.targets"
              Pack="true"
              PackagePath="build" />
        <None Include="packaging\runtimes\**\*.*">
            <Pack>true</Pack>
            <PackagePath>runtimes</PackagePath>
        </None>
    </ItemGroup>
</Project>
